import type { Metadata } from "next";
import "./globals.css";
import  Footer  from "../components/Footer";
import  Header  from "../components/Header";
import { Inter } from 'next/font/google';
import Script from 'next/script';
import'./main.ts';

const inter = Inter({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700','800','900'],
});

export const metadata: Metadata = {
  title: "Auralis -Lamnding page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
       <body className={`${inter.className} bg-[#101010] min-h-screen overflow-x-hidden`}>
        {/* fontawesome */}
        <Script src="https://kit.fontawesome.com/f060e66234.js" crossOrigin="anonymous" />
        <div className="header-gradient "></div> 
        <Header />
     <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
