"use client";
import Image from "next/image";
import '../app/globals.css';
const brands = [
  "/images/brand/68a0dd67a72ed147463e0653_Brands Logo 03.svg",
  "/images/brand/68a0e007d76c4ad323a90989_Brands Logo 04.svg",
  "/images/brand/68a1ad39dafd6cd106a837ac_Brands logo 02.svg",
  "/images/brand/68a1b1d5eaa832d6e6542eca_Brands logo 05.svg",
  "/images/brand/68a1b407cff662105c0513af_Brands logo 01.svg",
];

export default function BrandSection() {
  return (
    <section className="overflow-hidden py-16 max-w-3xl mx-auto relative">
      <p className="text-center text-lg md:text-xl text-white font-normal">
        Over{" "}
        <span className="text-[#1ee19b] font-normal">
          20,000,000
        </span>{" "}
        product images generated by brands worldwide.
      </p>

      <div className="absolute left-0 top-0 h-full w-28 bg-gradient-to-r from-[#101010] to-transparent z-10"></div>
      <div className="absolute right-0 top-0 h-full w-28 bg-gradient-to-l from-[#101010] to-transparent z-10"></div>

      <div className="scroll-brands flex gap-10 my-16 ">
        {brands.concat(brands).map((logo, idx) => (
          <Image
            key={idx}
            src={logo}
            alt="brand"
            className={`h-8 hover:scale-105 transition duration-300 ${
              idx % brands.length === brands.length - 1 ? "h-10" : ""
            }`}
            width={160}
            height={40}
            priority={idx < brands.length}
            
          />
        ))}
      
      </div>
    </section>
  );
}
